### ISSUE TITLE
Line54: ${FILENAME}.pub or $FILENAME

### ISSUE THREAD

**Issue by liudragonfly** [centic9/generate-and-send-ssh-key#4]
[Line54](https://github.com/centic9/generate-and-send-ssh-key/blob/master/generate-and-send-ssh-key.sh#L54): ${FILENAME}.pub or $FILENAME?

**Comment by centic9** [comment]
The `-i` specifies the local private keyfile that is used when doing the ssh-connect as part of ssh-copy-id. So it should be without `.pub`.

However I am not sure if the `-i $FILENAME` is even useful here as we do not yet have the public-key copied over at that time and thus it will ask for the password anyway. So maybe it can just be removed similar to the non-ssh-copy-id steps at line 52.

**Comment by centic9** [comment]
Hm, seems `-i` has completely different meaning in `ssh` and `ssh-copy-id`, which is a bit confusing. 

I need to take a closer look, but you are likely right.

**Comment by centic9** [comment]
Adjusted now, thanks for the note.
