### ISSUE TITLE
Permission denied (publickey) 

### ISSUE THREAD

**Issue by NataliaDiaz** [centic9/generate-and-send-ssh-key#5]
when running main script ./generate-and-send-ssh-key.sh 
How can I add my ssh-key to the server when I cannot connect to it?

**Comment by centic9** [comment]
This project only can enable key-based login correctly if you are able to log in via username/password currently. It cannot magically connect to your host and transfer the key, if it would be possible this would be a major security issue. 

There is no way to connect with a key before it got uploaded via other means first. If your provider/admin does not provide you with username/password, he will need to provide some other way of uploading the ssh-key before you can connect.
