### ISSUE TITLE
ssh-copy-id fails, fall back to manual

### ISSUE THREAD

**Issue by Safihre** [centic9/generate-and-send-ssh-key#6]
Thanks so much for this script!
Needed to connect 2 MRI scanners and the special modified linux version did not work with the standard commands. In particular it does have the `ssh-copy-id` command, but it's somehow broken. Since the system is completly locked-down (understandably) I could not re-install or update.
I had to modify the script to fall back to the manual way and this worked.
Maybe that would be a general good solution? If not found or fails, try manual?

Just a suggestion 👍

**Comment by centic9** [comment]
Can you give a bit more detail about which "manual way" you mean?

**Comment by Safihre** [comment]
Sorry I meant manual copy, as it's called here:
https://github.com/centic9/generate-and-send-ssh-key/blob/master/generate-and-send-ssh-key.sh#L112

**Comment by centic9** [comment]
Ok, and what was wrong with your version of ssh-copy-id? Because it seems the file was available, but not usable for some reason. 

Anything that we could use to better detect if ssh-copy-id is usable? Do you have the output of the script when it failed to work?

**Comment by Safihre** [comment]
It reported `bad configuration option: umask`

But I think other problems could probably also occur, judging from the Google results.

**Comment by centic9** [comment]
We now fall back to the manual copying whenever ssh-copy-id reports an error.
